### PR TITLE
Edit the message the bot sends in `ping.ts`

### PR DESCRIPTION
**Pull request by YoruNoKen**
In `message-commands/ping.ts`, the code attempts to edit the message the author sent, resulting in an error on line 12.
This pr fixes that bug

### CODE REVIEW

**Comment by xHyroM** [comment]
Does this also work for interaction(slash) command?

**Comment by YoruNoKen** [comment]
> Does this also work for interaction(slash) command?

you don't need it for interaction commands, `interaction.editReply()` works just fine, as the interaction message belongs to the bot.

**Comment by xHyroM** [comment]
Ohh, i see, it's in `src/message-commands/ping.ts` i was just confused by my framework. Thanks!

**Review by xHyroM — COMMENTED** [review]
d

**Pull request merged**
